### ISSUE TITLE
m3u8 with extension code

### ISSUE THREAD

**Issue by Abdel-ilah** [clappr/clappr#1465] opened 2017-07-15 08:39 UTC
hello developers,
i try to play m3u8 url on clappr, but this url has an extension code after .m3u8 
like:
`http://93.174.93.84:8081/live/bein11-hq/chunks.m3u8?nimblesessionid=54038635&wmsAuthSign=c2VydmVyX3RpbWU9Ny8xNS8yMDE3IDc6MTQ6MDcgQU0maGFzaF92YWx1ZT14YjhLWEhUQ3BNUGpNaWhhYVpZY1ZRPT0mdmFsaWRtaW51dGVzPTYwJmlkPTE4OC4xMTQuMTEwLjE4JnN0cm1fbGVuPTE0`

But it work on PotPlayer.exe & VLC
What is this code for? and i can play it on Clappr?

thank you

**Comment by kslimani** [comment] 2017-07-15 09:03
@Abdel-ilah your stream url is returning a "403 Forbidden" http error code. (_well at least from my location_).

Just go to [Clappr demo page](http://clappr.io/demo/) : open browser dev. tools (_should be **F12** key_) and click on "network tab". Then enter the following javascript code in page and click on "run" button.

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://93.174.93.84:8081/live/bein11-hq/chunks.m3u8?nimblesessionid=54038635&wmsAuthSign=c2VydmVyX3RpbWU9Ny8xNS8yMDE3IDc6MTQ6MDcgQU0maGFzaF92YWx1ZT14YjhLWEhUQ3BNUGpNaWhhYVpZY1ZRPT0mdmFsaWRtaW51dGVzPTYwJmlkPTE4OC4xMTQuMTEwLjE4JnN0cm1fbGVuPTE0',
  height: 360,
  width: 640
});

player.attachTo(playerElement);
```

Do you get also a 403 network error ?

**Comment by Abdel-ilah** [comment] 2017-07-15 09:27
Thank you kaslimani
yes, it's work fine
can you try with this please?
`https://7dkwdw.mycloud.to/1/ZEWphKzr2joqPWgt132ihg/0/d/m/o/dqo4mw/hls/360/360.m3u8?e=1500116400`

**Comment by kslimani** [comment] 2017-07-15 22:23
The server for `https://7dkwdw.mycloud.to/1/ZEWphKzr2joqPWgt132ihg/0/d/m/o/dqo4mw/hls/360/360.m3u8?e=1500116400` does not send "CORS" headers in response. This is why it does not work.

Just try your URL on Clappr demo page while having browser dev. tools console open (_you will see the error messages_).

**Comment by Abdel-ilah** [comment] 2017-07-16 13:39
Thank you

**Comment by momipnd** [comment] 2017-09-21 11:15
http://oasisiptv.com:6969/live/skype/QvfhlC9dxz/4699.m3u8
I run it with clapper player.  The issue is I can play the m3u8 URL, but when i will play it multiple it stops. Only this URL play form one device. I want to play multiple.

**Comment by Abdel-ilah** [comment] 2017-09-21 14:56
for play it on multi devices you should ask the IPTV provider for activate re-streaming option, you need more $$

**Comment by leandromoreira** [comment] 2017-09-21 15:05
@Abdel-ilah  can we close this issue?

**Comment by Abdel-ilah** [comment] 2017-09-21 15:06
Yes boss

**Closed** 2017-09-21 17:21 UTC

**Comment by ikniazi23** [comment] 2019-02-05 13:49
I have same issue when i play this link on ip at which i capture it from an app it open successfully but when i try to access it from another ip it says Forbbiden.

Please tell me the solution.Thanks in advance.

http://cdn.jazztv.pk:8087/app/SaudiSunnah-141/live/141M/chunks.m3u8?nimblesessionid=38413230&wmsAuthSign=c2VydmVyX3RpbWU9Mi81LzIwMTkgOToxOTowMCBBTSZoYXNoX3ZhbHVlPUVmZWROdy9JQ2hSdkxoSkpMVFJnd0E9PSZ2YWxpZG1pbnV0ZXM9MQ==
