### ISSUE TITLE
VOD HLS, after play clappr download all fragments from server 

### ISSUE THREAD

**Issue by wicherdt** [clappr/clappr#401] opened 2015-03-24 09:41 UTC
If hit play or pause , clappr download all fragments listed in m3u8 file.
By this wasted a lot of CDN transfer.
How to set buffer size.
Tested on Windows 8 , firefox.

**Comment by flavioribeiro** [comment] 2015-03-30 02:43
We wanted to keep VoD HLS with the same behavior of progressive download. Since this is a [flashls](https://github.com/clappr/flashls/blob/dev/src/org/mangui/hls/HLSSettings.as#L45) option, we can expose this as embed parameter. I saw that endless prefetching can cause memory handling exceptions on IE11 so I'm +1 for adding this feature.

**Comment by towerz** [comment] 2015-03-30 03:32
@flavioribeiro +1 for that. I was looking at the HLS playback code and I think it's easy enough to add it as  an embed parameter. The playback should only check for the parameter presence and setting the max buffer length based on that parameter, on the `setFlashSettings` method.

**Comment by wicherdt** [comment] 2015-03-30 10:30
Seems OK

**Comment by towerz** [comment] 2015-03-30 23:01
@wicherdt @flavioribeiro I just pushed ff8b05c09e96e4d44476acbf8c77323eaaa00734 which adds a new parameter `maxBufferLength`, defining the buffer length in seconds. The default behavior is still to download all fragments.

I believe this closes the issue. Please let me know if there's anything else to add.

@flavioribeiro @thiagopnts @leandromoreira What do you think of changing the default behavior to use a limited buffer length instead of downloading the entire video? I think mimicking the progressive download behavior should be optional.

**Comment by wicherdt** [comment] 2015-03-31 11:48
"maxBufferLength" working OK. Thank you.

**Comment by irongomme** [comment] 2015-03-31 16:24
Is that parameter works too for HLSPlayer.swf ?

**Comment by wicherdt** [comment] 2015-03-31 16:30
I tested only HLS VOD

**Comment by towerz** [comment] 2015-03-31 17:29
@irongomme This parameter is for the HLS playback, which is the playback abstraction for HLSPlayer.swf.

**Comment by towerz** [comment] 2015-04-02 20:32
Closing, everything is working OK.

**Closed by towerz** 2015-04-02 20:32 UTC
Labels: enhancement

**Comment by manuelchiarlo** [comment] 2015-04-24 07:42
I'm using the CDN Clappr build, but the issue is still present.
This is my parameter:

var player = new Clappr.Player({source: "http://media.dlz.ovh/hls/salute/salute-puntata.m3u8", parentId: "#player", autoPlay: true, maxBufferLength:5});

tested on firefox and chrome for mac.

thanks

**Comment by wicherdt** [comment] 2015-04-24 07:45
You must use latest version from github with commits.
