### ISSUE TITLE
Clappr not working in Firefox

### ISSUE THREAD

**Issue by baragamer** [clappr/clappr#610] opened 2015-10-25 21:47 UTC
Clappr works in all devices using HLS but not in Windows Phone and In firefox, the web browser

**Comment by flavioribeiro** [comment] 2015-10-25 23:07
@baragamer firefox is disabling flash by default and since we're still waiting for it to enable MSE by default (hopefully next month) we're not using hls.js on it. Said that, try enabling flash and the playback should work. Regarding windows phone, I don't have access to a device with it so let's wait for someone to ask for details and try to reproduce.

**Comment by leandromoreira** [comment] 2015-10-27 17:32
Just a heads up:

* Firefox 42 will enable MSE by default
* There is no whitelist anymore ; "we won't be adding new sites to the whitelist"

http://www.ghacks.net/2015/08/06/mozilla-to-enable-media-source-extensions-mse-for-all-websites-in-firefox-42/

https://bugzilla.mozilla.org/show_bug.cgi?id=778617

**Comment by flavioribeiro** [comment] 2015-11-03 04:29
FYI Firefox 42 is schedule for tomorrow!

**Comment by flavioribeiro** [comment] 2015-11-15 18:11
@baragamer are you trying to play on firefox for windows phone?

**Closed** 2016-01-17 12:39 UTC
