### ISSUE TITLE
Vast and Clappr?

### ISSUE THREAD

**Issue by PostMalone** [clappr/clappr#1621] opened 2018-04-06 18:13 UTC
**Browser**: Chrome (Latest version)

**OS**: Windows 10

**Clappr Version**: Latest version

**Steps to reproduce**:

Hi, i want to know if it's possible to get Vast to work in Clappr player. I've tried to repos but had no luck.

**Comment by leandromoreira** [comment] 2018-04-06 20:33
Yes, I think @towerz is using it, is that right?

**Comment by PostMalone** [comment] 2018-04-06 22:03
Dear @towerz i'd really appreciate if you can help me somehow. I just can't get it to work. Maybe i'm using the wrong Plugin. Thanks!

**Comment by leandromoreira** [comment] 2018-04-06 23:04
@PostMalone what plugin are you using that provide VAST for clappr?

**Comment by leandromoreira** [comment] 2018-04-06 23:05
https://github.com/mycujoo/clappr-vast-plugin

or 

https://github.com/vix-simplex/clappr-vast-ad-plugin ?

**Comment by PostMalone** [comment] 2018-04-07 10:02
@leandromoreira i'm using https://github.com/mycujoo/clappr-vast-plugin

Here is my demo: http://f1livegp.stream/vast/player.php

I think something is wrong in my source code.

**Comment by leandromoreira** [comment] 2018-04-07 13:45
Did you notice any error message on server side or client side? It's only way for people to help you.

**Comment by PostMalone** [comment] 2018-04-07 13:50
well, clappr player wont show up, this is my code:

`

  | <html>
-- | --
  | <head>
  | <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
  | <script src="https://cdn.jsdelivr.net/clappr.chromecast-plugin/latest/clappr-chromecast-plugin.js"></script>
  | <script type="text/javascript" src="http://f1livegp.stream/vast/vast-ads.js"></script>
  | <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
  | </head>
  | <body>
  | <div id="ppp"></div>
  | <script>
  | var playerElement = document.getElementById("ppp");
  | var player = new Clappr.Player({
  | source: 'http://103.252.220.40:8081/live/live/playlist.m3u8',
  | height: "100%",
  | width: "100%",
  | mediacontrol: {seekbar: "#00A2DE", buttons: "#00A2DE"},
  | parentId: "#ppp",
  | mimeType: "application/x-mpegURL",
  | autoPlay: false,
  | plugins: {
  | 'core': [VastAds, LevelSelector, ChromecastPlugin]
  | },
  | VastAdsConfig: {
  | AdXMLUrl: 'https://www.vidcpm.com/watch.xml?key=5066a2f1eb6ed8e63acf7a0aaa95909a&custom=%7B%27width%27%3A%27'+$(window).width()+'%27%2C%27height%27%3A%27'+$(window).height()+'%27%7D&cb=3&vastref=f1livegp.stream'
  | }
  | });
  | </script>
  |  
  | <script async src="https://www.googletagmanager.com/gtag/js?id=UA-112765408-1"></script>
  | <script>
  | window.dataLayer = window.dataLayer \|\| [];
  | function gtag(){dataLayer.push(arguments);}
  | gtag('js', new Date());
  |  
  | gtag('config', 'UA-112765408-1');
  | </script>
  | </body>
  | </html>

`

**Comment by leandromoreira** [comment] 2018-04-07 15:16
It's hard to help you if you don't post the error logging message here, you can see them at your browser's console.

**Comment by towerz** [comment] 2018-04-07 15:26
@PostMalone could you fix your code input as well? We can't actually read it since it's not escaped properly and GitHub is formatting it weirdly. For multi-line inputs, you need to escape it with ` ``` ` instead of a single one.

Your exception description is also not well formatted. Could you do the same to it as well?

From what I can see, the problem seems to be the `Clappr`  global not being defined when instantiating the plugins. The LevelSelector, Chromecast and VastAds plugins are all getting the same exception.

**Comment by towerz** [comment] 2018-04-07 15:32
@PostMalone from what I've seen, the problem is the order of your `script` includes. The Clappr script should be loaded before the plugins (since all plugins depend on the `Clappr` global being loaded).

You're loading the scripts like this:
```
 <head>
 <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
 <script src="https://cdn.jsdelivr.net/clappr.chromecast-plugin/latest/clappr-chromecast-plugin.js"></script>
 <script type="text/javascript" src="http://f1livegp.stream/vast/vast-ads.js"></script>
 <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
 </head>
```

The right order would be something like this:
```
 <head>
 <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
 <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
 <script src="https://cdn.jsdelivr.net/clappr.chromecast-plugin/latest/clappr-chromecast-plugin.js"></script>
 <script type="text/javascript" src="http://f1livegp.stream/vast/vast-ads.js"></script>
 </head>
```

**Comment by towerz** [comment] 2018-04-07 15:34
@PostMalone I've edited your comments to fix the code/log formatting.

**Comment by PostMalone** [comment] 2018-04-07 15:39
hi, thanks for reply, i've changed the <head></head> codes but i still do not see the player. Just a blank page.

Log:

```vast-ads.js:81 Uncaught TypeError: Cannot read property 'UICorePlugin' of undefined
    at Object.<anonymous> (vast-ads.js:81)
    at __webpack_require__ (vast-ads.js:30)
    at Object.<anonymous> (vast-ads.js:57)
    at __webpack_require__ (vast-ads.js:30)
    at vast-ads.js:50
    at vast-ads.js:53
    at webpackUniversalModuleDefinition (vast-ads.js:9)
    at vast-ads.js:10
(anonymous) @ vast-ads.js:81
__webpack_require__ @ vast-ads.js:30
(anonymous) @ vast-ads.js:57
__webpack_require__ @ vast-ads.js:30
(anonymous) @ vast-ads.js:50
(anonymous) @ vast-ads.js:53
webpackUniversalModuleDefinition @ vast-ads.js:9
(anonymous) @ vast-ads.js:10
player.php:21 Uncaught ReferenceError: VastAds is not defined
    at player.php:21
(anonymous) @ player.php:21
```

**Comment by towerz** [comment] 2018-04-07 16:02
@PostMalone this error still has nothing to do with the player itself. The error occurs before instantiating it. The `VastAds` global is `undefined`.

You should always wait for all globals to be loaded before trying to instantiate the player. Instead of calling `new Clappr.Player(...)` right away, you should wait for the document to be fully loaded before calling.

**Comment by PostMalone** [comment] 2018-04-07 16:07
hmm, how can i do that?

**Comment by towerz** [comment] 2018-04-07 16:32
@PostMalone just change your player call to `window.onload`. Since you're loading everything synchronously, I believe it would work.

```
<script>
window.onload = function() {
  var playerElement = document.getElementById("ppp");
  var player = new Clappr.Player({
    source: 'http://103.252.220.40:8081/live/live/playlist.m3u8',
    height: "100%",
    width: "100%",
    mediacontrol: {seekbar: "#00A2DE", buttons: "#00A2DE"},
    parentId: "#ppp",
    mimeType: "application/x-mpegURL",
    autoPlay: false,
    plugins: {
      'core': [VastAds, LevelSelector, ChromecastPlugin]
    },
    VastAdsConfig: {
      AdXMLUrl: 'https://www.vidcpm.com/watch.xml?key=5066a2f1eb6ed8e63acf7a0aaa95909a&custom=%7B%27width%27%3A%27'+$(window).width()+'%27%2C%27height%27%3A%27'+$(window).height()+'%27%7D&cb=3&vastref=f1livegp.stream'
    }
  });
};
 </script>
```

**Comment by PostMalone** [comment] 2018-04-07 16:48
@towerz no luck buddy. Player wont load at all (blank page). Whatever, just wont use Clappr then :)

**Comment by towerz** [comment] 2018-04-07 17:01
@PostMalone ok then, feel free to try again whenever you feel like it. As I told you, it's not actually related to Clappr, it related to the order of loading the global symbols in the page.

Since I cannot assure you that the VAST plugin works (I've never used it), I won't be able to assist you other than trying to help you with the plugin loading sequence.

I'll close the issue for now. Feel free to re-open it or comment if you keep trying and find any further issues.

**Closed by towerz** 2018-04-07 17:01 UTC
Labels: answered, question, wontfix

**Comment by MarioAzevedo** [comment] 2022-09-09 23:28
<html>
    <head>
  <title>Clappr Player</title>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
  <script type="c3da1cede2fd09c29cc9e718-text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="c3da1cede2fd09c29cc9e718-text/javascript"></script>
  <script type="text/javascript" src="https://tezgoal.com/clappr-google-ima-html5-preroll-plugin.js"></script>
</head>
 
<body>
  <div id="player"></div>
  <script>
    var TAG =
      "https://www.videosprofitnetwork.com/watch.xml?key=6f8112e2f06f6adb1827fbed45182d92";
    var player = new Clappr.Player({
      source: "https://v3.soft4game.com/o1/stream76/chunks.m3u8",
      watermark: "https://stream.tezgoal.com/watermark.png",
      watermarkLink: "https://twitter.com/intent/follow?screen_name=tezgoaI",
      mute: false,
      autoPlay: false,
      height: '100%',
      width: '100%',
      parentId: "#player",
      position: 'bottom-left',
      mediacontrol: {seekbar: '#F9C226',buttons: '#F9C226'},
      plugins: [ClapprGoogleImaHtml5PrerollPlugin],
      googleImaHtml5PrerollPlugin: {
        tag: TAG,
        autostart: true,
      },
    });
  </script>
</body>
</html>

**Comment by MarioAzevedo** [comment] 2022-09-09 23:28
<html>
    <head>
  <title>Clappr Player</title>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
  <script type="c3da1cede2fd09c29cc9e718-text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="c3da1cede2fd09c29cc9e718-text/javascript"></script>
  <script type="text/javascript" src="https://tezgoal.com/clappr-google-ima-html5-preroll-plugin.js"></script>
</head>
 
<body>
  <div id="player"></div>
  <script>
    var TAG =
      "https://www.videosprofitnetwork.com/watch.xml?key=6f8112e2f06f6adb1827fbed45182d92";
    var player = new Clappr.Player({
      source: "https://v3.soft4game.com/o1/stream76/chunks.m3u8",
      watermark: "https://stream.tezgoal.com/watermark.png",
      watermarkLink: "https://twitter.com/intent/follow?screen_name=tezgoaI",
      mute: false,
      autoPlay: false,
      height: '100%',
      width: '100%',
      parentId: "#player",
      position: 'bottom-left',
      mediacontrol: {seekbar: '#F9C226',buttons: '#F9C226'},
      plugins: [ClapprGoogleImaHtml5PrerollPlugin],
      googleImaHtml5PrerollPlugin: {
        tag: TAG,
        autostart: true,
      },
    });
  </script>
</body>
</html>

**Comment by MarioAzevedo** [comment] 2022-09-09 23:29
`<html>
    <head>
  <title>Clappr Player</title>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js"></script>
  <script type="c3da1cede2fd09c29cc9e718-text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="c3da1cede2fd09c29cc9e718-text/javascript"></script>
  <script type="text/javascript" src="https://tezgoal.com/clappr-google-ima-html5-preroll-plugin.js"></script>
</head>
 
<body>
  <div id="player"></div>
  <script>
    var TAG =
      "https://www.videosprofitnetwork.com/watch.xml?key=6f8112e2f06f6adb1827fbed45182d92";
    var player = new Clappr.Player({
      source: "https://v3.soft4game.com/o1/stream76/chunks.m3u8",
      watermark: "https://stream.tezgoal.com/watermark.png",
      watermarkLink: "https://twitter.com/intent/follow?screen_name=tezgoaI",
      mute: false,
      autoPlay: false,
      height: '100%',
      width: '100%',
      parentId: "#player",
      position: 'bottom-left',
      mediacontrol: {seekbar: '#F9C226',buttons: '#F9C226'},
      plugins: [ClapprGoogleImaHtml5PrerollPlugin],
      googleImaHtml5PrerollPlugin: {
        tag: TAG,
        autostart: true,
      },
    });
  </script>
</body>
</html>`
