### ISSUE TITLE
HLS stream does not work in Chrome for Android

### ISSUE THREAD

**Issue by Infrox** [clappr/clappr#1896] opened 2020-01-21 06:52 UTC
**Browser**: Chrome 79.0.3945.116

**OS**: Android 9

**Clappr Version**: 0.3.8

**Steps to reproduce**:
`self.player = new Clappr.Player({width:200,height:200,chromeless:true,parent:self.element,source: url,autoPlay:true,muted:false});`

here is the error emmited by PLAYER_ERROR:
```
{
  description: 'PIPELINE_ERROR_DECODE: video decoder reinitialization failed',
  level: 'FATAL',
  origin: 'hls',
  scope: 'playback',
  raw: {},
  code: 'hls:3',
  UI: {
    title: 'Could not play video.',
    message: 'There was a problem trying to load the video.'
  }
}
```

**Comment by joaopaulovieira** [comment] 2020-08-06 23:21
Hi @Infrox can you share the media you used when this error occurred?

**Comment by asheroto** [comment] 2020-09-17 09:57
Works for me in Chrome for Android as of 0.4.0

**Comment by joaopaulovieira** [comment] 2021-02-05 20:35
Thanks @asheroto!

Closing due to the lack of the possibility of reproduction. If the reported behavior continues, reopen this issue.

**Closed by joaopaulovieira** 2021-02-05 20:35 UTC
Labels: bug
