### ISSUE TITLE
Double Tap fullscreen on chrome android

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#965] opened 2016-04-28 14:39 UTC
In addition to #391 , i've got a trouble with double tap on chrome android : 
- With the fullscreen mediacontrol => No problems , it works as expected
- With double tap, the player disapear, and i have to reload the page

I've tried it too on cdn.clappr.io, and the result in a little bit different but i think this is the same issue, something with the 100% width and height. We can see the browser trying to ask if we autorize the fullscreen mode, but disapear instantly. There must be a missing event something, or something is triggered twice ...

**Comment by alouane** [comment] 2016-11-05 22:17
I think that's the 100% height, it's not properly translated by the browser, it's like a 0px rendering

**Comment by kslimani** [comment] 2016-11-05 23:30
I can confirm i also had this behaviour on chrome android 6.0.1 (tested with Samsung Galaxy S5).
But the bug does not always happen. (i was not able to determine the exact cause to reproduce the bug yet).
Also sometime on double tap, the player does not go fullscreen but get bigger in height (very strange, again i am still digging on fiding the way to reproduce).

**Comment by alouane** [comment] 2016-11-05 23:34
Try to install crosswalk, I'h juste installed, it worked for the first fullscreen action but once out, the problem persist, fullscreen button makes the player vanish again

**Comment by REELcoder** [comment] 2019-02-20 21:01
An now? Anyone with an idea how to how to achieve such basic functionality?

**Comment by joaopaulovieira** [comment] 2020-10-31 00:23
I cannot reproduce the reported behavior. Is this still a problem?

**Comment by joaopaulovieira** [comment] 2021-02-05 19:46
Closing due to the lack of the possibility of reproduction. If the reported behavior still continues, reopen this issue.

**Closed by joaopaulovieira** 2021-02-05 19:46 UTC
Labels: bug, to confirm
