### ISSUE TITLE
[HLS] incorrect container dimensions after exit fullscreen mode

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#900] opened 2016-03-19 03:01 UTC
**Browser**: Firefox 45.0 on Fedora 23 x86_64, Firefox 45.0.1 on Windows 10 x86_64, Firefox 44.0 on Mac OS X  10.9 Mavericks

**Clappr Version**: 0.2.38 - 0.2.40  with hlsjs and flashls playbacks

**Steps to reproduce**:

* open   http://cdn.clappr.io/ with Firefox browser and change source to http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8
* click play, then fullscreen button and exit fullscreen mode (ESC)
* player container dimensions are not returned to original sizes

![clappr_firefox](https://cloud.githubusercontent.com/assets/222185/13896292/3fc87f1e-ed8f-11e5-92fc-5955f8c5c668.png)

**Comment by towerz** [comment] 2016-03-19 18:59
@me-vlad actually, this is not a bug. You set the player size to occupy 100% of its parent dimensions.

Since the player container style in the test page only has a minimum width, the player container will fill the entire parent height, and use the minimum width (320 px, I think).

If you set the player width/height to fixed values, it will resize correctly.

**Comment by me-vlad** [comment] 2016-03-19 19:10
@towerz on cdn.clappr.io player has fixed width and height values
This issue related only for Firefox, I cant reproduce it on Chrome, IE, Edge etc.

**Comment by towerz** [comment] 2016-03-19 21:23
@me-vlad I see, sorry about that, I just got the error here. It seems to be either a problem with the player `destroy` method or with the `fullscreenchange` event listeners. I'm still trying to isolate the problem.

If you load the test page using the source in the query string (http://cdn.clappr.io/?src=http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8), the problem does not seem to happen.

**Comment by towerz** [comment] 2016-03-19 21:31
I just found what happens exactly. The problem occurs only when loading through the `run` button in the test page. It's actually related to how the player behaves when two instances are embedded in a page, after one of the instances is destroyed. The event listeners responsible for handling the fullscreenchange event are destroyed and no other listener is registered.

To reproduce the problem:
- create two player instances
- destroy one of them
- enter fullscreen and then exit

**Comment by me-vlad** [comment] 2016-03-19 23:16
@towerz  may be I missed something but I cant log fullscreen events on cdn.clappr.io adding 

``` javascript
player.on(Clappr.Events.MEDIACONTROL_FULLSCREEN, function() { console.log("FULLSCREEN!") });
```

**Comment by towerz** [comment] 2016-03-20 03:12
@me-vlad actually, the `MEDIACONTROL_FULLSCREEN` event is triggered by the media control when the user activates fullscreen. It's not triggered on the player object, so the right way to do this is
```javascript
player.core.mediaControl.on(Clappr.Events.MEDIACONTROL_FULLSCREEN, function() { console.log("FULLSCREEN!") });
```
But even doing this, the exit fullscreen event won't be triggered when pressing ESC.

**Comment by towerz** [comment] 2016-03-20 04:07
@me-vlad I just pushed a change including the PLAYER_FULLSCREEN event. Now you can just do this:
```javascript
player.on(Clappr.Events.PLAYER_FULLSCREEN, function(fullscreen) {console.log('fullscreen is', fullscreen ? 'on' : 'off')});
```
b3a2468 solves the problem you reported. Please let me know if it works for you

**Comment by me-vlad** [comment] 2016-03-20 14:05
@towerz  thanks, it works on firefox, i'll test master build with other browsers

**Comment by me-vlad** [comment] 2016-03-30 15:18
ref: https://github.com/clappr/clappr/issues/911

**Comment by towerz** [comment] 2016-03-31 19:10
Closing this issue, since 0.2.41 includes this fix.

**Closed by towerz** 2016-03-31 19:10 UTC
Labels: bug
