### ISSUE TITLE
Player restarting after pausing

### ISSUE THREAD

**Issue by Kzanadeus** [clappr/clappr#1419] opened 2017-05-23 07:52 UTC
Hi,

I use clappr for a while now and it's working fine. Now, when i start a video in a player and then change source and cant pause then play the player because it restart the video from the begining.

It's doing it all the time.

If someone knows a way to prevent that it'll be great.

Best regards.

**Comment by leandromoreira** [comment] 2017-05-23 11:27
how do you change source?

**Comment by Kzanadeus** [comment] 2017-05-23 11:44
With the js function load

Ex : player.load('mavideo.mp4');

**Comment by leandromoreira** [comment] 2017-05-23 16:58
@Kzanadeus when you load a new video it'll restart the playback, you can inform that you don't want it to autoStart or even where to start to play.

What behavior do you expect when you change the source?

**Comment by Kzanadeus** [comment] 2017-05-23 18:03
In fact, the problem is not that the video start to the begining when i change the source. After i changed the source once, if you pause the player and then replay it, it will start from the begining not at the position it has been paused. It only append after i changed the source. The first video, everything is perfect.

**Comment by kslimani** [comment] 2017-05-23 18:45
@Kzanadeus i am not sure to understand the behaviours you described. Do you have any code sample or demo page to share ?

**Comment by leandromoreira** [comment] 2017-05-23 18:48
Are these the steps to reproduce this behavior?

1. start any video, play it
1. and then change the source
1. start to watch it
1. pause the video and unpause

The expected outcome would be continue to play from where it was when it was paused but does it starts again from the begininig?

**Comment by Kzanadeus** [comment] 2017-05-23 20:17
Exactly.

**Comment by leandromoreira** [comment] 2017-05-23 22:05
@Kzanadeus were you able to reproduce this behavior at http://clappr.io/demo/ changing the default source to http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8 ?

**Comment by leandromoreira** [comment] 2017-05-23 22:11
@Kzanadeus I tried the following code at the  http://clappr.io/demo/  and it seems to work as expected:

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

setTimeout(
  function() { 
    player.load('http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8',null,true) 
  }, 8000);
```

**Comment by Kzanadeus** [comment] 2017-05-24 08:26
@leandromoreira I tried your code on your demo page and yes it's working fine.

I'm searching a way to create a page that you can try yourself because the behavior is different inside my project.

Anyway, thanks for your reactivity.

**Comment by skylord220** [comment] 2017-06-26 21:20
Suffering from similar issue. In my case source video URL was relative to site root (not absolute). Browser converts it to absolute. Then after playback resume HTML5Video.prototype._setupSrc compares elements' and config source URLs and as they differ (relative from config and absolute from element) - replaces elements' one resulting in video restart.

**Comment by kslimani** [comment] 2017-06-27 08:47
@skylord220 can you provide your browser + os name & version and which Clappr version you are using ?

**Comment by kslimani** [comment] 2017-06-27 09:01
@skylord220 : you are correct, i was able to reproduce the issue. Thank you for report ! 👍

**Comment by leandromoreira** [comment] 2017-06-27 11:11
due to #1451 we'll close this one

**Closed by leandromoreira** 2017-06-27 11:11 UTC
Labels: provide-more-info
