### ISSUE TITLE
timeupdate event shouldnt be fired before play event

### ISSUE THREAD

**Issue by leandromoreira** [clappr/clappr#1183] opened 2016-10-14 18:54 UTC
https://github.com/leandromoreira/clappr-stats/pull/6

https://github.com/clappr/clappr/blob/142e58f7d407635386d2ecc53df98b3249ef8866/src/playbacks/hls/hls.js#L173-L175

**Comment by joaopaulovieira** [comment] 2018-02-22 21:04
@leandromoreira, I think the problem is when `_onTimeUpdate()` try to check if those times (current and recieved) are the same.

`this._lastTimeUpdate` is set to `null` on constructor and consequently, `isSame` will be `null` too.
https://github.com/clappr/clappr/blob/553e4a2793b44486d3b1d13856ab5cb994cb9835/src/playbacks/hls/hls.js#L109-L113
https://github.com/clappr/clappr/blob/553e4a2793b44486d3b1d13856ab5cb994cb9835/src/playbacks/hls/hls.js#L294-L301

`this.getCurrentTime()` and  `this.getDuration()` return 0 at the the first moment.

If `_lastTimeUpdate` is a object with the initial parameters of the same value, the desired behavior would be obtained.

Like: `    this._lastTimeUpdate = { current: 0, total: 0 }`

What you think?

**Comment by leandromoreira** [comment] 2018-02-22 21:41
I'm sorry, I'm having a hard time to follow, this was a very long time ago! 😆 

Do you still agree with the statement `timeupdate event shouldn't be fired before play event`? (regardless how this is going to be fixed) Or semantically we should and can fire a `timeupdate` before `play` event?

**Comment by joaopaulovieira** [comment] 2018-02-22 23:38
Yes, I lose the focus of the issue investigating what happened :see_no_evil:
I tested the approach of only firing the `timeupdate` after a `play` and the same problem occurs at the moment of comparing the times.
You agree with the solution above or have another approach to suggest?

**Comment by leandromoreira** [comment] 2018-02-23 00:46
I'm with you! ✌️

**Comment by kslimani** [comment] 2018-02-23 13:45
@joaopaulovieira i think you first assumption may be correct.
As long as `(isEqual(update, this._lastTimeUpdate))` condition is true, the `PLAYBACK_TIMEUPDATE` event is not triggered. (ie: ensure this condition is true when playback is created)

**Comment by joaopaulovieira** [comment] 2018-02-23 18:21
@towerz , what you think?

**Comment by joaopaulovieira** [comment] 2018-03-09 16:02
Can we close this issue @leandromoreira, @towerz ?

**Closed** 2018-03-09 16:15 UTC
Labels: bug, enhancement, refactoring
