### ISSUE TITLE
Problems when switching between live and not, dvr controls disappear

### ISSUE THREAD

**Issue by osk** [clappr/clappr#357] opened 2015-02-10 17:09 UTC
Serving HLS and if I go from being live to seeking back, I lose the dvr controls.

If the stream catches up, it goes back to being live and the duration and position disappear but the live/dvr controls don't come back

**Comment by flavioribeiro** [comment] 2015-02-10 21:12
hey @osk can you send me your stream source? you can do it privately sending to flavio <at> bem.tv

**Comment by flavioribeiro** [comment] 2015-02-10 21:24
this issue is probably related to #297

**Comment by osk** [comment] 2015-02-11 09:51
OK, I've sent you an example

**Comment by chriswiggins** [comment] 2015-02-14 20:02
I'm having the same problems here with an HLS stream that has 1 hour worth of entries in the playlist (but its a moving window)

**Comment by flavioribeiro** [comment] 2015-02-16 21:12
@osk @chriswiggins you are able to reproduce it on both firefox and chrome?

**Comment by chriswiggins** [comment] 2015-02-25 20:27
Hi @flavioribeiro, Yes this happens in both Chrome and Firefox

**Comment by flavioribeiro** [comment] 2015-03-09 21:06
@chriswiggins @osk can you guys try with this new version (0.0.107) at http://cdn.clappr.io and tell me if it's fixed?

**Comment by towerz** [comment] 2015-04-16 01:20
@chriswiggins @osk Have you tried again testing on the latest version at http://cdn.clappr.io? Does this behavior still occur?

**Comment by towerz** [comment] 2015-05-27 15:44
Since the problem doesn't happen anymore, I'll close this issue for now.

**Closed by towerz** 2015-05-27 15:44 UTC
Labels: bug
