### ISSUE TITLE
Navbar should close when user clicks an option

### ISSUE THREAD

**Issue by soustab10** [clappr/clappr#2081] opened 2022-10-11 12:00 UTC
**Browser**: All Browsers

**OS**: Windows 10

**Clappr Version**: 0.3.8

**Steps to reproduce**:

1. Go to http://clappr.io/
2. Click on hamburger nav.
3. See error on clicking any button.

Screenshots:
![image](https://user-images.githubusercontent.com/95632583/195083809-c4a82083-19db-4684-b5d2-b65f0828db6a.png)

**Comment by najeebkp** [comment] 2022-10-16 06:20
hi @soustab10  please assign this to me.

**Comment by leaofelipe** [comment] 2022-10-21 17:48
Hi Guys! Thank you for creating this issue.
@najeebkp feel free to send us a PR! 🎉

**Comment by Kathuria** [comment] 2022-10-30 09:05
@leaofelipe : Can you please assign this issue to me?

**Comment by jeramiahgcoffey** [comment] 2022-11-20 02:50
Looks like this is no longer an issue?

**Comment by brinobruno** [comment] 2023-01-17 00:01
@leaofelipe, I'd like to get started on that feature, from what I can see when user clicks to any button in navigation it still won't close automatically (remove blur on body and close nav again)

Is that the expected behavior? Could I work on that?

**Comment by leaofelipe** [comment] 2023-01-17 01:09
Hi, @brinobruno! Your contribution is very welcome! This is a bug and your PR will solve it 🥇 

Also, when your PR is merged, please send us another one, adding your name and email to the **Clappr Contributors** file! https://github.com/clappr/clappr/blob/dev/CONTRIBUTORS

**Comment by brinobruno** [comment] 2023-01-17 22:27
Hey @leaofelipe, my changes are ready to go, but it's on another repository, I created another issue to be able to correctly reference it over there at clappr/website!

I'll be creating a PR there now :)

**Comment by leaofelipe** [comment] 2023-01-18 01:49
Nice @brinobruno! 🎉🎉

**Comment by leaofelipe** [comment] 2023-01-18 01:55
Merged ✅ 
https://github.com/clappr/website/pull/3

**Closed by leaofelipe** 2023-01-18 01:55 UTC
Labels: bug
