### ISSUE TITLE
Stop Video Live

### ISSUE THREAD

**Issue by MohammaedAlani** [clappr/clappr#1944] opened 2020-07-15 07:22 UTC
**Browser**: FILL WITH YOUR BROWSER (ex: Chrome Version 46.0.2490.80, Firefox Version 3.5.6, IE 11)
chrome 83.0.4103.116 (Official Build) (64-bit)

**OS**: FILL WITH YOUR OS (ex: Mac OS 10.11.1, iOS9, android4.5)
Windows and macOS

**Clappr Version**: 0.4.0

**From Console Error**:
[warn][hlsjs: non-fatal error occurred]
{evt: "hlsError", data: {…}}
data:
buffer: 0.07487199999999916
details: "bufferStalledError"
fatal: false
type: "mediaError"
proto: Object
evt: "hlsError"
proto: Object

[warn][hlsjs: non-fatal error occurred]
{evt: "hlsError", data: {…}}
data:
details: "bufferSeekOverHole"
fatal: false
frag: e {_url: "http://10.254.253.6:8008/sport/ch3/ch3_108014929.ts", _byteRange: null, _decryptdata: null, _elementaryStreams: {…}, deltaPTS: 0.03999999999999204, …}
reason: "fragment loaded with buffer holes, seeking from 71.929454 to 72.074"
type: "mediaError"
proto: Object
evt: "hlsError"
proto: Object

**Comment by joaopaulovieira** [comment] 2020-08-06 23:13
Hi @MohammaedAlani  can you share the media you used when this error occurred?

**Comment by MohammaedAlani** [comment] 2020-08-06 23:21
I'm sorry this not public, but on Vlc it work perfectly no error no stop.

**Comment by joaopaulovieira** [comment] 2020-08-07 00:12
Can you reproduce the problem with some other media that we can use for testing?

**Comment by joaopaulovieira** [comment] 2021-02-05 20:55
Closing due to the lack of the possibility of reproduction. If the reported behavior continues in one file that can be shared, reopen this issue.

**Closed by joaopaulovieira** 2021-02-05 20:55 UTC
Labels: bug
