### ISSUE TITLE
.m3u8 does not play in IE 11

### ISSUE THREAD

**Issue by chrisprog20** [clappr/clappr#1496] opened 2017-08-23 15:18 UTC
**Browser**: IE 11

**OS**: Windows 7

**Clappr Version**: 0.2.71  
(loaded from https://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js)

The clappr player does not load the .m3u8 in IE 11.
This is as it does not load the swf-File from the cdn-Server and tries to load it from the root directory of the localhost. Applying the property "baseUrl" in the Clappr.Player initialization does not help either.
This issue is related to issue #1480.

The clappr player loads this file type also in IE 11 _if loaded_ from https://cdn.jsdelivr.net/clappr/latest/clappr.min.js which delivers version _0.2.66_.

**Comment by kslimani** [comment] 2017-08-30 08:23
Duplicate of #1480.

**Closed** 2017-08-30 10:30 UTC
