### ISSUE TITLE
Hitting the spacebar on an input field plays video and no space character is in input field

### ISSUE THREAD

**Issue by davidplappertvb** [clappr/clappr#435] opened 2015-05-07 18:46 UTC
To recreate the problem:
- Embed a clappr video
- put an <input type='text' /> box in the same <html> page
- place your cursor inside the input box, hit the space bar

Expected Result:
- to place a space character in the input box

What happens:
- video begins to play whit cursor is in input box, and no space character is input.

Demo this issue:
- visit https://dev.finishlineplanner.com/
- place your cursor in the field that says "Your eMail Address"
- hit the space bar

**Comment by towerz** [comment] 2015-05-08 02:32
@davidplappertvb I see you are using clappr version 0.0.114. This problem has been solved in commit 1d5be4b4d175f14385b7944a8a210198436ebcc3.

You can just update your clappr version to 0.0.115, which has this problem fixed already.

I'll close this issue, since it's a duplicate of #426.

Please let me know if you have any problems regarding keyboard input.

**Closed by towerz** 2015-05-08 02:32 UTC
