### ISSUE TITLE
Encrypted Live HLS

### ISSUE THREAD

**Issue by irongomme** [clappr/clappr#425] opened 2015-04-22 13:20 UTC
I've got a strange behavior with encrypted HLS : 

With chrome (windows 7 and linux), sometimes i've got sound only, and sometimes i've got picture only.
Under iOs and android, everything works fine, and that situation let me think that this is a flash issue !

Here is a playlist sample : 
```
#EXTM3U
#EXT-X-MEDIA-SEQUENCE:1963
#EXT-X-ALLOW-CACHE:NO
#EXT-X-VERSION:2
#EXT-X-KEY:METHOD=AES-128,URI="https://sslhls.m6tv.cdn.sfr.net/hls-key/w9_hls_aes.bin",IV=0xe00828cca2551372b13abfe48a1cc60f
#EXT-X-TARGETDURATION:9
#EXTINF:9,
http://hls.m6tv.cdn.sfr.net/hls-live/streams/livepkgr/events/_definst_/w9_hls_aes/w9_hls_aes_856Num1963.ts
#EXTINF:9,
http://hls.m6tv.cdn.sfr.net/hls-live/streams/livepkgr/events/_definst_/w9_hls_aes/w9_hls_aes_856Num1964.ts
#EXTINF:9,
http://hls.m6tv.cdn.sfr.net/hls-live/streams/livepkgr/events/_definst_/w9_hls_aes/w9_hls_aes_856Num1965.ts
#EXTINF:9,
http://hls.m6tv.cdn.sfr.net/hls-live/streams/livepkgr/events/_definst_/w9_hls_aes/w9_hls_aes_856Num1966.ts
#EXTINF:9,
http://hls.m6tv.cdn.sfr.net/hls-live/streams/livepkgr/events/_definst_/w9_hls_aes/w9_hls_aes_856Num1967.ts
#EXTINF:9,
http://hls.m6tv.cdn.sfr.net/hls-live/streams/livepkgr/events/_definst_/w9_hls_aes/w9_hls_aes_856Num1968.ts
```

And the stream uri : 
https://sslhls.m6tv.cdn.sfr.net/hls-live/livepkgr/_definst_/m6_hls_aes/m6_hls_aes_856.m3u8

What do you think about ?

**Comment by towerz** [comment] 2015-04-22 21:51
@irongomme It really seems to be a flash issue. We're still investigating why there were some problems with our flashls fork and whether this is a bug we introduced.

**Comment by towerz** [comment] 2015-04-30 17:40
@irongomme I've opened an issue on flashls to get some help discovering the reason this problem occurs. Probably @mangui will have a better insight of why the player presents this behavior.

**Comment by neilkinnish** [comment] 2015-05-01 21:04
I have a similar issue.

Playlist and ts files served over SSL will not play at all, through non SSL everything works fine.

**Comment by towerz** [comment] 2015-05-01 22:38
@neilkinnish Thanks for the info, I'll check if I can reproduce this behavior.

**Comment by towerz** [comment] 2015-05-27 15:41
@irongomme @neilkinnish It seems the latest version of flashls fixed this weird behavior. I just pushed an updated HLSPlayer.swf with this version.

Already tested it with your stream (https://sslhls.m6tv.cdn.sfr.net/hls-live/livepkgr/_definst_/m6_hls_aes/m6_hls_aes_856.m3u8) and it worked. There was only one behavior that I noticed, which is the either the audio or the video starts playing first, and apparently on the next segment the playback stabilizes completely, playing both audio and video. This doesn't happen 100% of the time, but it's still noticeable at times.

**Comment by irongomme** [comment] 2015-05-27 16:00
Thx @towerz  for feedback, i test it right now !

**Comment by irongomme** [comment] 2015-05-27 16:18
This is better ! :+1: 

I've no sounds for the 1st segment, but then its ok

**Comment by mangui** [comment] 2015-05-27 16:27
i would guess it is an AES Initialization Vector issue.
when IV is wrong, first 16 bytes are wrong (usually first 16 bytes of TS fragment is the PAT. the PAT contains the PMT PID ... if the PMT PID is incorrect because of bad IV it will not be found ...) but the following bytes are correct;
see http://crypto.stackexchange.com/questions/2865/why-does-cbc-decryption-with-a-wrong-iv-still-give-readable-results

**Comment by towerz** [comment] 2015-05-27 18:31
Makes sense, perhaps that's why I couldn't reproduce the error in my test setup.

**Comment by towerz** [comment] 2015-07-06 04:01
Closing this issue, seems to be a problem related to a specific stream.

**Closed by towerz** 2015-07-06 04:01 UTC
