### ISSUE TITLE
BUG? lot of pixels...

### ISSUE THREAD

**Issue by hijuuijj** [clappr/clappr#1632] opened 2018-04-30 19:24 UTC
Try this video: https://atresplayerp-i.akamaized.net/lasextampp/bitrate_4.m3u8

Lot of pixels with the latest version of Clappr. (https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js)
No pixels using native hls player.

**Comment by hijuuijj** [comment] 2018-05-01 14:27
Same problem with HLS.js

**Comment by leandromoreira** [comment] 2018-05-01 16:01
@hijuuijj nice, please [try to see if there no problem with your stream at all](https://github.com/clappr/clappr/blob/master/doc/TROUBLESHOOTING.md#common-steps-to-verify-issues).

**Comment by hijuuijj** [comment] 2018-05-03 23:00
With Chrome PC using Clappr:

**Pixelated:** https://cdn.jsdelivr.net/npm/clappr@latest/dist/clappr.min.js
Not pixelated: https://cdn.jsdelivr.net/clappr/latest/clappr.min.js

There is something wrong with the first one (npm)

**Comment by leandromoreira** [comment] 2018-05-04 02:00
@hijuuijj maybe it's with hls.js, have you tried to use hls.js alone to see if the problem happens again?

**Comment by leandromoreira** [comment] 2018-05-04 02:00
about the npm difference that's weird =/

**Comment by LaQuay** [comment] 2018-05-05 12:51
Same problem here.

**Comment by leandromoreira** [comment] 2018-05-05 14:35
Did you test it on [hls.js demo page](https://video-dev.github.io/hls.js/demo/)?

**Comment by hijuuijj** [comment] 2018-05-05 14:57
Commented here too:

https://github.com/video-dev/hls.js/issues/1695

**Comment by LaQuay** [comment] 2018-05-05 15:41
@leandromoreira Yes, same problem. It is a hls.js related problem... (Stream works fine with Video.js)

**Comment by vagnervjs** [comment] 2018-05-15 13:05
Closing this issue since it's a hls.js related problem

**Closed by vagnervjs** 2018-05-15 13:05 UTC
Labels: wontfix

**Comment by hijuuijj** [comment] 2018-07-02 22:06
Is there any news? Atresmedia group has disabled the option to play the stream with clappr/hls.js (crossdomain)... so now it's only playable with HLS Native Playback extension... but it's still pixelated.

http://livepull1.secure.footprint.net/antena3mpp/bitrate_4.m3u8

**Comment by flavioribeiro** [comment] 2018-07-03 01:05
I can reproduce the green artifacts on hls.js but not on safari. 
@hijuuijj I suggest you open an issue on github.com/video-dev/hls.js, this issue should be addressed there.
