### ISSUE TITLE
icons: mediacontrol styling option regression after switching to svg icons

### ISSUE THREAD

**Issue by me-vlad** [clappr/clappr#903] opened 2016-03-20 14:24 UTC
**Browser**: ANY

**Clappr Version**: git master https://github.com/clappr/clappr/commit/6fde7d05f79cf6c4f370a391af2af848dc7dc84c

**Steps to reproduce**:

* install clappr from latest git (after https://github.com/clappr/clappr/commit/d6d47b6db6e53d3f2b00fda71e72e3ee2c823bc1) 
* add to player config
```
 mediacontrol: {seekbar: "#E113D3", buttons: "#66B2FF"}
```
* buttons (controlbar buttons ,poster play icon) styling not changed

**Comment by towerz** [comment] 2016-03-23 21:56
@me-vlad thanks for reporting. I just pushed 	a15861a which should fix this regression. Please let me know if this works for you.

**Comment by me-vlad** [comment] 2016-03-23 23:02
@towerz  just tested with  a15861a - svg fill color still #010101 
Also I think poster plugin needs to be changed for big play button color styling.

**Comment by towerz** [comment] 2016-03-24 14:39
@me-vlad agreed. The poster controls should follow the media control styling.

About the svg fill color, the actual color is being set through css. You can ignore this attribute, since browsers always override these attributes with the values defined through css. You can check this in the path element style in the browser inspector.

I just pushed a small fix in the fullscreen style (12aa33a), it should be working correcly.

**Comment by me-vlad** [comment] 2016-03-24 17:35
@towerz testd on https://github.com/clappr/clappr/commit/f45bfe2d196a0c0b2ab42f361470fd26e4b12aa4

big play button (poster plugin), fullscreen control and volume control, HD indicator, play/pause - styling fixed
stop button - #010101

**Comment by towerz** [comment] 2016-03-24 19:53
Nice catch, @me-vlad, I forgot to check the play/stop toggle. Just pushed the fix.

**Comment by towerz** [comment] 2016-03-24 19:54
If everything is ok, I'll add some tests for this regression before closing the issue.

**Comment by me-vlad** [comment] 2016-03-24 20:18
@towerz stop button fixed for me, thanks

**Closed** 2016-03-30 15:17 UTC
Labels: bug
