### ISSUE TITLE
flashls performance issues

### ISSUE THREAD

**Issue by operutka** [clappr/clappr#631] opened 2015-11-03 10:55 UTC
Our customers experience some performance issues when playing video using clappr/flashls combination. There is a lot of messages like:
`WARN:FPSController:drop FPS ratio >0.2,drop/displayed:10.0,11.0 in the last 5000ms`

in the web browser log. There are big artifacts in the video every time the drop/displayed ratio gets close to one. It would be nice to have an option to disable frame dropping completely (even if it would cause delayed frames) but most of all we need a way to lower CPU consumption.

There are two options in the `flash.media.Video` class - `smoothing` and `deblocking`:
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/Video.html

Setting the `smoothing` parameter to `false` and `deblocking` to `1` would allow us to save some CPU load and improve our user experience (even if the video would look a bit worse). Unfortunately, we cannot access these options as the Video object is probably created somewhere inside your src/playbacks/flashls/public/HLSPlayer.swf blob.

Would it be possible to expose these options, so we could set them as we wish?

**Comment by flavioribeiro** [comment] 2015-11-03 15:44
@operutka can you send us the stream url and browser/pc confs?

**Comment by operutka** [comment] 2015-11-03 16:22
@flavioribeiro some of the streams can be found here: 
http://www.eagles.org/Cams/FloridaNest.html

You can get the stream URL from your browser's console. It has always the following format:
http://{...}.angelcam.com/{...}/playlist.m3u8?token={...}

note: the token in the URL is valid only for a limited period of time, you have to get a new one from your browser after the token's expiration

The problem has been reported across all platforms and browsers. We don't have any statistics about HW configurations.

**Comment by flavioribeiro** [comment] 2015-11-03 16:59
Ok, I'll try to reproduce at my side. Just curious if you're using the latest version of clappr, but even so, we still need to update our version of flashls. I'll work on that soon.

**Comment by operutka** [comment] 2015-11-03 17:10
Thanks. We're using the latest version of clappr but this is more a question of the Flash VM and its standard library. Exposing those options in your API would be great anyway so we could play with it on our own.

BTW we have tried to hack the blob a little and added instructions for setting those two options in the org.mangui.chromeless.ChromelessPlayer class in the _onStageVideoState method (the else part of the first branch) and we can confirm ~50% CPU usage drop (at least in Firefox on Linux).

**Comment by flavioribeiro** [comment] 2015-11-03 17:12
I'll confirm with the rest of the team if we're using [this](https://github.com/clappr/flashls) fork of flashls or if there's another one and update with latest @mangui:dev's branch, I'll let you know asap

**Comment by flavioribeiro** [comment] 2015-11-03 19:11
@operutka, b798074734995339cddd99a4f0fe28b6c91f0c23 updates our swf to the latest version of flashls, can you verifiy if performance is still an issue for you?

**Comment by leandromoreira** [comment] 2015-11-03 19:27
@operutka another thing you can test is to force the usage of `software decoder`.

At first it sounds counterintuitive but we noticed that often the performance issues were related to many switches between hardware and software decoder and if you force software it stops these swaps.

```javascript
new Clappr.Player({... , useHardwareVideoDecoder: false});
```

**Comment by operutka** [comment] 2015-11-09 10:32
I'm sorry for my late response. I was a bit busy last week.

@leandromoreira Thank you for the tip, we have already tried that but this is not the case. We have disabled the HW acceleration for some browsers as it caused frequent crashes. The issue we're talking about here is related to the SW decoder. Unfortunately, some of our clients have quite weak HW for SW decoding and it causes the decoder starts dropping frames. Sometimes, when the number of dropped frames gets above some threshold, the decoder loses essential information for decoding following frames and artifacts appear in the displayed video.

@flavioribeiro There is no performance problem in clappr or flashls. As I already mentioned, the problem is caused by weak HW of some of our clients. What we're trying to do is to minimize CPU load by switching off some non-essential decoder features such as smoothed scaling and loop filter (i.e. deblocking). In order to do this, we need an access to the `smoothing` and `deblocking` fields of the Video object.

**Comment by cowai** [comment] 2015-11-21 14:37
I also have choppy fullscreen video on linux with latest clappr. With videojs + flashls 0.3.5 it is smooth. But newer versions of flashls is choppy.

**Comment by mangui** [comment] 2015-11-21 20:54
@cowai in order to assess your statement, could you install Adobe Scout (available for free) and post your profiling results highlighting the performance issue between different release of flashls ?

**Comment by cowai** [comment] 2015-11-22 11:24
Is Adobe Scout  available for linux? I tried to find it but seems to be for osx and windows.

**Comment by mangui** [comment] 2015-11-22 17:08
Mmm unfortunately not ... but remote profiling might be doable. Or maybe the perf issue is not linux specific ?

**Comment by cowai** [comment] 2015-11-23 09:08
@mangui 
This is only with Flash 11.2.202.548 (Firefox). In Chrome (bundled with its own flash), it looks smooth.

**Comment by cowai** [comment] 2015-11-23 10:56
Is it easy to set flashls 0.3.5 only for flash 11.2? Is there a working 0.3.5 swf player that works with latest clappr?

**Comment by mangui** [comment] 2015-11-23 10:58
well, we need to understand what is going on. a bunch of optimizations have been done in the 0.4.x as well... there might be something wrong, either on Linux specifically, or with any flash 11.2

**Comment by cowai** [comment] 2015-11-23 11:24
I installed 11.2 in OS X and both videojs4 with flashls 0.35 and latest clappr where choppy. (Though not in chrome) So I think maybe this is a linux only issue. I will test with Windows 7 later.

**Comment by cowai** [comment] 2015-11-23 12:00
Update:
I tried with 11.2 in Windows 7 on the same machine as the one with linux, and it was smooth there. So this is a linux only problem I think. Also, I don't have ubuntu to test with either. This is Arch Linux with LXQT as the desktop. As people are upgrading to Firefox 42 and MSE I guess this will not be a big problem ;)

**Comment by leandromoreira** [comment] 2015-12-02 02:09
I'm gonna close this one since it seems that it was mostly related to flash+linux

**Closed by leandromoreira** 2015-12-02 02:09 UTC
Labels: to confirm
