### ISSUE TITLE
Fullscreen on Android Chrome closed when clicked on player.

### ISSUE THREAD

**Issue by canny-wasp** [clappr/clappr#1245] opened 2016-12-29 11:15 UTC
**Browser**: Chrome 55.0.2883.91

**OS**: Android 6.0.1

**Clappr Version**: latest (http://cdn.clappr.io/latest/clappr.js on http://cdn.clappr.io) 

**Steps to reproduce**:
* open http://cdn.clappr.io in Chrome on Android
* play video and resize to fullscreen
* click on player container
* I was expecting "pause without exit from fullscreen" but instead it shows "exit from fullscreen without pause"

This reproduced at http://cdn.clappr.io/

**Comment by kslimani** [comment] 2016-12-29 11:52
It is working for me with Android 6.0.1 and Chrome 54.0.2840.85. _(Samsumg Galaxy S5)_.

I will upgrade Chrome to latest and test again.

**Comment by kslimani** [comment] 2016-12-29 12:06
@leandromoreira  I upgraded to Chrome 55.0.2883.91 and i confirm strange behaviours :

* if i click on poster image to start video, the player resize using the document height (it seems)
* i have the same bug as @vix-simplex when clicking on video in fullscreen

**Comment by kslimani** [comment] 2016-12-29 12:59
@vix-simplex i am not sure. It require some debug with Clappr touch events.

**Comment by kslimani** [comment] 2016-12-29 13:15
I can confirm also it is related to Google Chrome version 55.0.2883.91 (tested on Galaxy Tab 4 with Android 5.0.2)

**Comment by joaopaulovieira** [comment] 2016-12-29 20:08
https://github.com/madrobby/zepto/issues/1238

**Comment by vix-simplex** [comment] 2016-12-30 09:18
@leandromoreira 
I did. Steps (to make sure I do everything right):
* git clone https://github.com/clappr/clappr.git
* cd clappr
* npm install
* git checkout update_zepto_005
* npm run start
* open http://192.168.0.74:8080/webpack-dev-server/ in my Chrome in Android by wifi (192.168.0.74 - IP my desktop in local network, phone and desktop in same local network)
* problem is reproduced - when fullscreen playing I clicked on player and fullscreen closes.

**Comment by kslimani** [comment] 2016-12-30 09:57
@vix-simplex i think you need to change git branch __before__ install npm package _(in order to use the updated package.json)_

**Comment by kslimani** [comment] 2016-12-30 10:52
@leandromoreira i tried the `update_zepto_005` branch, but it seems something is wrong with this Zepto version because i get a `TypeError: f is undefined` with locahost:8080 demo page.

This error disallow Clappr module to load and of course it is followed by a `ReferenceError: Clappr is not defined`.

**Comment by vix-simplex** [comment] 2016-12-30 11:18
@kslimani I run "npm intsall" arter changing branch and received `TypeError: f is undefined` too.

**Comment by kslimani** [comment] 2016-12-30 11:23
@vix-simplex i think this error comes from zepto-clappr module, not Clappr itself.

@thiagopnts it would be nice if you could describe how you generate minfied version of zepto-clappr (to ensure it is the same way you do) so i could also experiment/debug this path.

**Comment by kslimani** [comment] 2016-12-30 14:23
@leandromoreira i tested with latest Zepto using [this method](https://github.com/clappr/clappr-zepto/issues/4#issuecomment-269776677) and i still have the fullscreen touch issue. _(it seems upgrading Zepto is not enough or i maybe missed something)_

**Comment by leandromoreira** [comment] 2016-12-30 17:09
@kslimani thank you, :) we'll need to check this deeper.

**Comment by thiagopnts** [comment] 2016-12-31 00:57
@kslimani I added instructions to the readme https://github.com/clappr/clappr-zepto/blob/master/README.md

**Comment by msyagli** [comment] 2017-01-24 13:13
any updates? :)

**Comment by leandromoreira** [comment] 2017-01-25 17:36
We @clappr/core are going to remove the `touch events` from [clappr-zepto](https://github.com/clappr/clappr-zepto) until we see another way to fix it.

Are you okay with that?

**Comment by msyagli** [comment] 2017-01-30 08:58
if it works, will be fine :)

**Comment by leandromoreira** [comment] 2017-01-30 13:22
Can you guys test it against the new version?

**Comment by kslimani** [comment] 2017-01-30 14:34
@leandromoreira with Samsung Galaxy S5 and Google Chrome `55.2883.91` using `cdn.clappr.io` demo page :

* VOD (mp4 & hls.js) :  in fullscreen video pause without exiting fullscreen mode (as expected)
* LIVE (hls.js) :  in fullscreen video stop and exiting fullscreen mode (as expected)
* LIVE with DVR (hls.js) :  in fullscreen video pause and "back to live" without exiting fullscreen mode (as expected)

Also, note that it require to "tap" __twice__ the screen in order to display mediacontrols or pause video because of the Google CAST feature. Basically, the first "tap" display the top left CAST icon, and the second "tap" is handled by Clappr.

This feature can be misleading because the CAST icon is not always displayed (i think it is a bug in Chrome not related to Clappr, but worth to mention).

**Comment by vix-simplex** [comment] 2017-01-30 14:41
@leandromoreira I confirm "twice clicks for pause", I reproduce this behavior too.

**Comment by leandromoreira** [comment] 2017-01-30 14:54
Thanks for the tests, we'll need to address these `touch events` problems, properly, in another issue. can we close it?

**Closed** 2020-01-24 05:21 UTC
Labels: bug, high-priority
