### ISSUE TITLE
Question about Firefox

### ISSUE THREAD

**Issue by primoitt83** [clappr/clappr#939] opened 2016-04-11 20:16 UTC
**Browser**:  Firefox 38

**OS**:  Linux Ubuntu 12.04

**Clappr Version**: latest

**Video**: http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8

**Video**: http://techslides.com/demos/sample-videos/small.ogv

Hello,

I'm trying test some videos in http://cdn.clappr.io/ and got some messages on console.

TypeError: Function.prototype.toString called on incompatible object clappr.min.js:3:17405
ReferenceError: Clappr is not defined

It's seems to happen only in older versions of Firefox (from 29 to 42).

Works fine on Firefox 43, 44 and 45.
Works fine on older versions like 25, 26, 27 and 28.

Is this an issue or a bug? 

Thanks in advance

**Comment by leandromoreira** [comment] 2016-04-12 00:05
@primoitt83 we've changed some JS libraries and one of them break the compatibility with Firefox older than 39.

@clappr/core do you think we should investigate this?

**Comment by towerz** [comment] 2016-04-13 00:32
@leandromoreira @primoitt83 it seems to be related to an issue on lodash that's already been fixed. Apparently, the offenders are lodash.result and lodash.uniqby. Both have been updated to version 4.3.0, but it probably wasn't included on Clappr 0.2.47.

I tested with Firefox on http://cdn.clappr.io (Clappr 0.2.47) and the same problem occurred, while testing on the same browser with current master (1419c45) the problem doesn't occur. I'll try to release another version as soon as I finish testing so we can fix this issue.

**Comment by leandromoreira** [comment] 2016-04-13 01:00
@primoitt83 can you test it against current master ? (then we can close it)

**Comment by PNixx** [comment] 2016-04-13 10:33
**Browser**: Firefiox 45.0.1
**OS**: Mac OS 10.11.4
**Clappr Version**: 0.2.47
**Video**: Any non-work address

Hello.
Event `Clappr.Events.PLAYER_ERROR` doesn't work, I try `PLAYBACK_ERROR` but it has not given the results.
![2016-04-13 13 25 44](https://cloud.githubusercontent.com/assets/1117351/14490549/7d94ba98-0184-11e6-966a-e8340f994d57.png)

**Comment by primoitt83** [comment] 2016-04-13 11:43
@leandromoreira I will do it as soon as possible!

@towerz thanks man!!!

**Comment by primoitt83** [comment] 2016-04-13 13:07
Hello again!

No luck!

TypeError: Function.prototype.toString called on incompatible object clappr.min.js:3:17405

ReferenceError: Clappr is not defined qualidade.html:65:10

O método getPreventDefault() não deve mais ser usado. No lugar, use defaultPrevented.

This is what i did it.

Download version 1419c45 

https://github.com/clappr/clappr/archive/1419c451428d2b0f2fa23b37ab6a4d2c37b6f2ec.zip

Unzip in my site's folder.

Copy the file clappr.min.js from folder /dist to site's root.

Create a html file.

Try to test a video but no luck :(

Did i miss something for make it work?

Thanks again

**Comment by leandromoreira** [comment] 2016-04-13 13:20
@primoitt83 can you test using this dist? This is the latest build http://www.filedropper.com/dist

Usually you could:

1. git clone https://github.com/clappr/clappr.git
2. npm install
3. npm run release
4. use dist/ folder

**Comment by primoitt83** [comment] 2016-04-13 13:31
@leandromoreira even using the dist,zip you uploaded i got the same error

TypeError: Function.prototype.toString called on incompatible object clappr.min.js:3:17423

ReferenceError: Clappr is not defined qualidade.html:65:10

O método getPreventDefault() não deve mais ser usado. No lugar, use defaultPrevented.

I'll try git method that you mentioned.

Thanks

**Comment by primoitt83** [comment] 2016-04-13 14:45
I've tryed git method and good news!!

Everything is working properly now on Firefox 38!!

Here's my results:

OGV - works!
WEBM - works!
MP4 - works!
FlasHLS - works!
HLS - doesnt work. Probably old Firefox is not compatible. Firefox 45 and Chrome 34 works fine

You Clappr's guys rock!!!

Thank you so much for help me out!!

Cheers!  :+1: :D

**Comment by leandromoreira** [comment] 2016-04-13 16:49
Thank you @primoitt83 soon we'll post a new version.

**Closed by leandromoreira** 2016-04-13 16:49 UTC
Labels: bug

**Comment by bikegriffith** [comment] 2016-04-20 16:47
@leandromoreira @towerz Any idea when you'll release a new version with this fix?  Thanks for all you do!

**Comment by bikegriffith** [comment] 2016-04-20 19:06
As I spoke, my Firefox updated itself to 45.0.2 and the issue is now fixed.

**Comment by leandromoreira** [comment] 2016-04-20 19:33
We're doing it right now @bikegriffith :)
