### ISSUE TITLE
LG G3 mobile video error

### ISSUE THREAD

**Issue by FDiskas** [clappr/clappr#665] opened 2015-11-12 14:37 UTC
The LG G3 phone default browser is Chrome mobile 34
The HLS video is not playing. Probably its trying to force the flash version but in android there is no flash at all.

**Comment by leandromoreira** [comment] 2015-11-13 23:01
@FDiskas usually Chrome at android [reports itself as mobile](https://github.com/clappr/clappr/blob/master/src/components/browser.js#L56). And since most of the androids support HLS natively [Clappr will chose](https://github.com/clappr/clappr/blob/master/src/components/loader/loader.js#L47) [html5_video](https://github.com/clappr/clappr/blob/master/src/playbacks/html5_video/html5_video.js#L263) instead of flash.

Can you provide more information about this issue? [like the console logs](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en)

I would like to kindly ask you to try to follow this [style of bug report](https://github.com/clappr/clappr#guideline-to-open-an-issue-bug):

**Comment by FDiskas** [comment] 2015-11-19 13:22
It could help http://developer.lgappstv.com/TV_HELP/index.jsp?topic=%2Flge.tvsdk.developing.book%2Fhtml%2FDeveloping+Web+App%2FDeveloping+Web+App%2FStreaming+Method.htm

**Comment by leandromoreira** [comment] 2015-11-19 13:35
Are you using webview in this case?

**Comment by FDiskas** [comment] 2015-11-19 14:22
The same device http://whatsmybrowser.org/b/HTYERUD

**Comment by FDiskas** [comment] 2015-11-19 14:51
[videojs](https://github.com/videojs/video.js) are playjing video correctly on this device with the same live stream

**Comment by leandromoreira** [comment] 2015-11-19 16:23
Thanks, @FDiskas knowing what OS/Browser is needed because we can reproduce it and try to fix it.

**Comment by bikegriffith** [comment] 2016-02-02 16:42
Has anyone had any luck confirming/reproducing this? We've seen a recent upswing in reports of playback issues on LG devices using our legacy video.js player.  Curious how widespread this is and if it's possible that LG did something to break HLS playback.

**Comment by leandromoreira** [comment] 2016-05-11 17:55
I assume this is fixed with hls.js

**Closed by leandromoreira** 2016-05-11 17:55 UTC
Labels: bug, to confirm
