### ISSUE TITLE
Auto seek Clappr

### ISSUE THREAD

**Issue by deepch** [clappr/clappr#1488] opened 2017-08-15 00:03 UTC
seek worked only loaded video?
I can use seek not load video?

**Comment by kslimani** [comment] 2017-08-15 01:05
If you want to "auto seek" video on load, take a look at the `autoSeekFromUrl` player option.

**Comment by deepch** [comment] 2017-08-15 01:22
I tried it but I could not use it.

**Comment by deepch** [comment] 2017-08-15 01:27
var player2 = new Clappr.Player({source: "http://171.25.233.50:8080/api/v1/stream/test/nvr/hls/1502715600/7200/index.m3u8?t=120",

I add ?t=120 and autoStartLoad: true,

not working on hls?

**Comment by kslimani** [comment] 2017-08-15 01:55
@deepch i think that `t` query parameter must be on page url, not on source url.

**Comment by deepch** [comment] 2017-08-15 08:27
So I tried the same and the same does not work.

http://ipeye.ru/test2.html?t=200

**Comment by kslimani** [comment] 2017-08-15 11:53
@deepch : thank you for providing demo page! I can confirm there is a little bug with player. It seems that playback is trying to seek video too soon. It is strange because it was working before.

In the meantime that feature is check and eventually fixed, please try the following workaround :
_(or adjust to your needs.)_

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://171.25.233.50:8080/api/v1/stream/test/nvr/hls/1502715600/7200/index.m3u8',
  height: 360,
  width: 640,
  autoPlay: true,
  events: {
    onReady: function() {
      this._cldt = 0;
      var c = this.core.getCurrentContainer();
      this._cld = function () {
        this._cldt = Clappr.Utils.seekStringToSeconds();
        if (this._cldt > 0) {
          setTimeout(function() {
            console.log('seek ' + this._cldt + ' seconds');
            this.seek(this._cldt);
          }.bind(this), 500);
        }
      };
      this.listenTo(c, Clappr.Events.CONTAINER_LOADEDMETADATA, this._cld);
    },
  }
});

player.attachTo(playerElement);
```

**Comment by perohu** [comment] 2018-02-19 08:11
I think this bug is still present, I've just run into this.

Here is my demo: https://player-infocam.infornax.hu/test-autoseek.html?t=120
It is not starting at 2 minutes, as it should
Will this bug be fixed in the future?

I can not make this work with the workaround above either
Workaround demo: https://player-infocam.infornax.hu/test-autoseek2.html?t=120

Thx!

**Comment by bercutes** [comment] 2018-07-20 12:47
t not work

**Comment by towerz** [comment] 2018-07-20 20:55
Strangely, I can't reproduce the problem in the Clappr demo page:

http://clappr.io/demo/?src=http://www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8&t=120.

I couldn't access your demo, @perohu, the video is failing to load.

@kslimani what kind of bug you've found?

**Comment by kslimani** [comment] 2018-07-20 21:51
hmmm, i think this issue was fixed by #1334 .

**Comment by kslimani** [comment] 2018-07-20 22:02
I tested on demo page with .m3u8 and .mp4 source and it worked for me too.

**Comment by bercutes** [comment] 2018-07-20 22:55
seekPercentage ( time ) maybe some example please, how implement in demo, in events?

**Comment by kslimani** [comment] 2018-07-20 23:35
just go to [demo page](http://clappr.io/demo/) and open javascript console (for example, F12 with Chrome browser). Then click on player play icon and type, for example in javascript console : `player.seekPercentage(50);` you will see the player seek to the middle of video.

**Closed** 2018-07-21 11:42 UTC
Labels: bug
