### ISSUE TITLE
Listening to player events

### ISSUE THREAD

**Issue by turanjanin** [clappr/clappr#411] opened 2015-04-10 10:25 UTC
Can you please give an example how to listen to player events? I want to monitor when user plays or stops playback and when playback errors occur.

**Comment by flavioribeiro** [comment] 2015-04-10 15:29
hi @turanjanin, I'm pretty sure that your question is related to #406. Assuming that your player instance is `p`, you can listen to the events by binding functions to it this way:
```javascript
p.listenTo(p, Clappr.Events.PLAYER_PLAY, function() { console.log("playing!") })
```
[Here](https://github.com/clappr/clappr/blob/master/src/base/events.js#L136:L143) is the list of available events.

**Comment by RadyAeg** [comment] 2015-04-11 23:14
Is there way to listen to some error event? I have problem to capture error condition (404 error for example).

**Comment by guzz** [comment] 2015-04-15 16:47
Hello, @flavioribeiro I´m trying to listen to the PLAYER_PLAY event, but it is not working. Do I have to install a plugin or build the player?

**Comment by flavioribeiro** [comment] 2015-04-15 16:53
hey @guzz, it seems that the guys needs to bump a new version in order to make this stuff work. I'm not in charge of this anymore, we need to wait for a new version.

**Comment by towerz** [comment] 2015-04-16 01:13
@guzz we're still fixing some errors and improving external plugin interfaces prior to releasing a new version. You could use the version on master to work with external events when waiting for a new release.

**Comment by towerz** [comment] 2015-04-16 01:14
@RadyAeg we still don't expose errors as events. I'll create an issue for that.

**Comment by towerz** [comment] 2015-05-02 05:08
@guzz @RadyAeg @turanjanin We just released version 0.0.115 with external events implemented. Now you can listen to the events as @flavioribeiro described. It also includes the event `Clappr.Events.PLAYER_ERROR` to listen for playback errors. We are still improving error handling, but there are some basic errors implemented already.

For external events, I would recommend using the `on` method instead of `listenTo`:
```
p.on(Clappr.Events.PLAYER_PLAY, function() { console.log("playing!") })
```
Please let me know if you have any more questions. I'll close this issue for now.

**Closed by towerz** 2015-05-02 05:08 UTC
Labels: question

**Comment by flavioribeiro** [comment] 2015-05-02 16:29
great job @towerz, congratz! :metal:

**Comment by josephharding** [comment] 2015-06-29 19:01
hey all, great experience with the player so far - I've got a question along the same lines for playback - if I want to know when my HLS stream has completed loading metadata, how can I listen for that event?

I've tried something like this, but with no luck:

player.on(Clappr.Events.PLAYBACK_LOADEDMETADATA, function() { console.log("metadata loaded"); });

Thanks!

**Comment by siddhesharolkar** [comment] 2016-06-28 08:04
HI, I am trying to implement network error handling.
I tried with :
player.listenTo(player, Clappr.Events.PLAYER_ERROR, function() { console.log("ERROR!") });
player.listenTo(player, Clappr.Events.PLAYBACK_ERROR, function() { console.log("playeback ERROR!") });
container.on(Clappr.Events.CONTAINER_ERROR, function() { alert('$$==>CONTAINER_ERROR'); });

but none of this working for me.
I am playing m3u8 file which is dynamically increasing.
In my case end tag is missing in m3u8 file.
So is it possible to get all these event without closing tag in m3u8 file?

**Comment by leandromoreira** [comment] 2016-06-28 12:41
@siddhesharolkar please don't double comment if you already opened an issue. https://github.com/clappr/clappr/issues/1052

**Comment by costa** [comment] 2016-08-02 09:07
1) Where can I find the list of *external* events (subscribeable with `#on`)?
2) What is the simplest option to listen to playback events? Must I go through the trouble of creating a plugin just for this?

**Comment by towerz** [comment] 2016-08-03 03:41
@costa you can find a list of all events on the `Events` class. The player _external_ events (the ones you can subscribe with `#on`) are the ones with `PLAYER_` prefix, like:
```javascript
var player = new Clappr.Player(...)
player.on(Clappr.Events.PLAYER_PLAY, function() { ... })
```
You can also listen to these events with the `events` parameter:
```javascript
var player = new Clappr.Player({
  events: {
    onPlay:  function() { ... }
  }
})
```
We have some issues with doc generation, which doesn't filter the events properly, so on the `Player` (class documentation)[http://clappr.github.io/classes/Player.html], for example, all internal events are exposed, instead of only the ones prefixed with `PLAYER_`.

**Comment by costa** [comment] 2016-08-05 08:54
@towerz thanks a lot! this would make a fine addition to the docs

**Comment by expandingfocus** [comment] 2018-11-08 09:52
Hi there.
I have trouble using the events with clappr and clappr-360. Maybe you can help me with it.

I want to add a redirect event after playback has ended, but unfortunately it won't work. Unfortunately I am not into js-coding, which is why I can't figure it out so easily.

This is my code:
`<script>
     
// The URL to the 360 video player 
var Video360Url = 'VIDEO_URL;


// Configure your Clappr player.
var PlayerInstance;
canAutoplay.video().then(function(o) {
var cap = o.result === true;
 PlayerInstance = new Clappr.Player({
source: Video360Url,
poster: 'POSTER_URL',
loop: 'false',
autoPlay: cap,
height: '100%',
width: '100%',
hideMediaControl: 'true',
chromeless: 'true',
allowUserInteraction: 'false',
preload: 'auto',
plugins: 
{
container: [Video360],
},
parent: '.player',
events: {
**ended**: function() { window.location.href = 'URL'; }
}
});
PlayerInstance.getPlugin('click_to_pause').disable();
});
</script>`

Neither "ended" nor "playback_ended" works. 

I also tried this:

`PlayerInstance.on(Clappr.Events.PLAYER_ENDED, function() {window.location.href = 'URL';})`

Can anyone see what the problem might be?

Thanks a lot!

**Comment by leandromoreira** [comment] 2018-11-08 11:08
@thiagopnts might help you out!

**Comment by thiagopnts** [comment] 2018-11-08 18:13
@expandingfocus hey, do you have a link to share were the issue is happening?
This works for me on http://thiago.me/clappr-360/:
```js
p.on(Clappr.Events.PLAYER_ENDED, () => window.location.href = 'URL');
```
where p is the player instance

**Comment by expandingfocus** [comment] 2018-11-13 10:59
> 
> 
> Thanks @thiagopnts for your reply!
> I've tried your code-snippet, but unfortunately it prevents the whole video from playing.
> Without the playerinstance.on the video playback starts.
> 
> You can find it with playerinstance.on here:
> https://www.enter-utopia.com/redirect/
> 
> This is the Page without:
> https://www.enter-utopia.com/
> 
> While I have you "on the phone", on mobile devices the video could not be decoded: "Error code: html5_video:3" - but it works with the clappr-example-video. What do I have to keep track of when rendering the video to work with clappr on mobile devices?
> And is there a way to set the "sensitivity" or configure the gyro for mobile, because if I move the mobile device slighty the 360° view totally freaks out.
> 
> Thanks a lot for your help and for the great work! I love the player :)

Well, I wasn't able to figure it out but I switched to videojs/pannellum, which suits all the parameters. anyway, thanks for your help!

**Comment by thiagopnts** [comment] 2018-11-27 16:59
sorry didn't have the take look at this, nice that pannellum worked out! I just pushed a new version of clappr-video360 that fixes the sensitivity issue
